# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0062c8a5b214633bf58267623f1e17c081e0544a6026cb6b5b65ca3a95e2a92241fd7e7e140c94f82b2fbcd1f92deaead77904a267809df234c6e8d98491243c

test:
  secret_key_base: 6e6e067818f4d1f70bda572d6878a59ca73c3f66b4bbb66d442542f5eda73d79520f21ea5e5da30d25c3651d7bd591fd5bb785b611d2e08bcc91871bf9461c03

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
